### ISSUE TITLE
100 Ohm Resistor on Display SCK is Not Eliminating Audio Noise?

### ISSUE THREAD

**Issue by dwestbury** [ElectroTechnique/TSynth-Teensy4.1#11]
I was hearing the popping and static noise that others were complaining about, so I went ahead and cut the PCB trace for the display clock (SCK) and added in a 100 Ohm resistor as noise reduction bridge, but to my ears there's nearly no difference? 

![IMG_2111](https://user-images.githubusercontent.com/61174362/102005577-d85cbb80-3ce7-11eb-83a2-ec5b11356ce6.jpeg)

Curious whether any other potential sources of noise are being investigated? In my case it's not terrible, but it is clearly perceptible.

**Comment by ElectroTechnique** [comment]
Hello Darrell, are you sure that you've cut completely through the SCK track? I've compared before and after, and the resistor does make a significant reduction in noise.

![20201218_141056](https://user-images.githubusercontent.com/50934180/102578134-cdb58280-413c-11eb-9227-6425d58aab48.jpg)

**Comment by dwestbury** [comment]
I actually peeled off the section of the copper trace leading from my cut on the board to the SDA pin.

Another area I need to investigate as a possible noise source is the dupont connector I made, so I can remove the teensy, rather than soldering it directly to the PCB. 

![E9144F28-1FCD-4CDD-A86F-923F13777B74](https://user-images.githubusercontent.com/61174362/102623020-d9d71b00-410f-11eb-8a25-83ca23061aab.jpg)

![775B7436-EEE0-4D44-9C8F-712CB97C6495](https://user-images.githubusercontent.com/61174362/102623027-dcd20b80-410f-11eb-963f-6de0fc969d84.jpg)

**Comment by nfroeschl** [comment]
It looks like I have the same problem here. The resistor is in place but the noise (volume independent) is still there. 
It look like it soming from any kind of computer USB. With a powerbank away from the computer it is not there.

Any solutions so far ?

**Comment by ElectroTechnique** [comment]
If it goes away when you change the power source, then it's coming from that. Be careful with ground loops.

**Comment by ElectroTechnique** [comment]
I can confirm that the V1.3 PCB which has a slightly re-routed display SCK track with a 100ohm resistor, is much quieter. Bypassing the 100ohm resistor increases the clock noise significantly.
