### ISSUE TITLE
SD card features

### ISSUE THREAD

**Issue by jvitkauskas** [ElectroTechnique/TSynth-Teensy4.1#119]
I am still waiting for my parts to arrive, so it might be an obvious thing, but: what kind of features require SD card? I see that provided presets take only 16k of space so any card size would be ok and speed rating does not matter at all? Also, can SD card files be accessed via USB or would I need to disassemble the case to insert/remove the card?

**Comment by ElectroTechnique** [comment]
Just a small card, speed doesn't really make any difference. No you need to remove the card. I couldn't see a way to make it visible to a pc as a storage device.
