### ISSUE TITLE
Can you still build one of these for $99?

### ISSUE THREAD

**Issue by CptanPanic** [ElectroTechnique/TSynth-Teensy4.1#124]
The README says it costs $99 to build, but stuff can't find singles of PCB or Front Panel. Does anyone know how to build less than the $355 for the full tindie kit.

**Comment by ElectroTechnique** [comment]
Hello, it'll cost around $99 just for a PCB and the parts to get it running. The enclosure is something else and depends on whether you make it yourself.

**Comment by CptanPanic** [comment]
> Hello, it'll cost around $99 just for a PCB and the parts to get it running. The enclosure is something else and depends on whether you make it yourself.

@ElectroTechnique 
Can you tell me how to get the PCB so I can get under the $99 including the parts?
