### ISSUE TITLE
Bug in effect_envelope

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [ElectroTechnique/TSynth-Teensy4.1#139]
As noted on the Teensy forum (https://forum.pjrc.com/index.php?threads/teensy-exponential-envelopes.75646/), there's a bug in the exponential envelope which shows up with a non-zero delay setting. I can't find a further upstream source than this one, though your commit log suggests there might be one... I think we're seeking Vince R. Pearson.

**Comment by ElectroTechnique** [comment]
Yes that's correct - [https://github.com/vipear](https://github.com/vipear)

**Comment by h4yn0nnym0u5e** [comment]
Thanks. Looks like he’s not been active for 3 years, would it be better to send the PR direct to you in this repo?

**Comment by ElectroTechnique** [comment]
Yes, that's ok. I'll update with any fixes.
