### ISSUE TITLE
Adding reverb?

### ISSUE THREAD

**Issue by philippejadin** [ElectroTechnique/TSynth-Teensy4.1#14]
I have no idea if there is processing power left and if it could be done easily, but it would be great a have a reverb effect available globally in the setting maybe?

What a cool sounding synth! (happy builder from just yesterday)

**Comment by antoniograzioli** [comment]
yeah, a nice reverb would be cool, but I guess there's not enoughr room on the Teensy to run a reverb algo ;-) 
I have been working on a similar poly-synth with reverb on a Teensy 3.2...anyway, we'll see...
