### ISSUE TITLE
No USB-MIDI on Mac?

### ISSUE THREAD

**Issue by antoniograzioli** [ElectroTechnique/TSynth-Teensy4.1#15]
I can program the Teensy of my TSynth using the latest .hex (2.10) successfully.
When I connect the Teensy to my PC, it is seen as a MIDI device and I can play it using MIDI-USB.
On Mac (High Sierra) , the TSynth is NOT seen as a MIDI device but as an Audio device (?!?!?)
(I am simply connecting the Tsynth using the Micro-USB port on the Teensy...)
Using the 5-pin DIN Connector for MIDI works on both platforms.

**Comment by ElectroTechnique** [comment]
Sorry, I can't test. Can you go to forum.pjrc.com and ask there, they'll be in a better position to help.
