### ISSUE TITLE
PRIORITY - Crashes

### ISSUE THREAD

**Issue by ElectroTechnique** [ElectroTechnique/TSynth-Teensy4.1#19]
Seem to be getting crashes, usually when changing patches. Could be on accessing SD card and loading patch data. Teensyduino 1.54 has improved SD card performance (Bill Greiman's SdFat library).

Never saw these crashes on T3.6 (PCB rev 1.1), but the code is different!

**Comment by callimero** [comment]
Yea, encountered these crashes too. Could never see a pattern and so.... I ignored it.

**Comment by ElectroTechnique** [comment]
TeensyDuino1.54 may be more promising, the current beta 9 works fine, just delete data_bandlimit_step.c from your TSynth folder because bandlimited waveforms are now included in the audio library.

**Comment by ElectroTechnique** [comment]
Haven't had a crash in a while, so closing this.
