### ISSUE TITLE
Volume control reverted back to controlling only headphone volume.

### ISSUE THREAD

**Issue by callimero** [ElectroTechnique/TSynth-Teensy4.1#7]
This comment made me wonder: In the build guide we connect the TRS Jacks to the Headphone Out on the Audio Board... I did not think about this so far, but there is also a Line Out which is more suitable for going to a Mixer, why not using this?

**Comment by ElectroTechnique** [comment]
Because people are more likely to want to attach to something where they can alter the volume and the headphone jack on the audio board is unsuitable (as is the USB socket on the Teensy) for repeated insertions.

**Comment by ElectroTechnique** [comment]
Actually the line out is probably better from a connection and noise point of view as it has a common ground with the rest of TSynth.
